server:
  port: 8080

spring:
  application:
    name: uwustream
  profiles:
    active: dev
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      minimum-idle: 10
      maximum-pool-size: 100
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true


nginx:
  hls_url: http://152.42.164.96:8088/hls/%s.m3u8